# Generated by Django 2.0.5 on 2018-08-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterestapp', '0002_auto_20180802_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
