# Generated by Django 2.0.5 on 2018-08-06 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pinterestapp', '0005_auto_20180806_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='pin',
            name='savedby',
        ),
        migrations.AddField(
            model_name='savedpins',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterestapp.Pin'),
        ),
        migrations.AddField(
            model_name='savedpins',
            name='savedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
