# Generated by Django 2.0.5 on 2018-08-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterestapp', '0007_auto_20180806_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='commented_by',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='commented_pin',
        ),
        migrations.RemoveField(
            model_name='savedpins',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='savedpins',
            name='savedby',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='SavedPins',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
